#!/usr/bin/env python3
"""Append the settlements verified on 2026-09-13 to the English source feed.

The operation is idempotent. Localized feeds are intentionally handled separately.
"""

from __future__ import annotations

import json
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
FEED = ROOT / "settlements.json"
RAW_ROOT = "https://raw.githubusercontent.com/Andrewegao/x9k2m4-static/main"
DATE_ADDED = "2026-09-13"


def make_record(
    *,
    id: str,
    title: str,
    company: str,
    total_amount: str,
    individual_payout: str,
    deadline: str,
    category: str,
    eligibility: str,
    bullets: list[str],
    proof_required: bool,
    proof_details: str,
    claim_url: str,
    source_url: str,
    summary: str,
    scope: str,
    case_info: str,
    status: str = "open",
    estimated_claim_time: str = "~5 min",
    payout_display_type: str = "details",
) -> dict:
    return {
        "id": id,
        "title": title,
        "company": company,
        "imageURL": f"{RAW_ROOT}/images/{id}.jpg",
        "totalAmount": total_amount,
        "individualPayout": individual_payout,
        "deadline": deadline,
        "category": category,
        "eligibility": eligibility,
        "eligibilityBullets": bullets,
        "proofRequired": proof_required,
        "proofDetails": proof_details,
        "claimURL": claim_url,
        "sourceURL": source_url,
        "summary": summary,
        "scope": scope,
        "caseInfo": case_info,
        "dateAdded": DATE_ADDED,
        "status": status,
        "claimCount": None,
        "logoURL": f"{RAW_ROOT}/logos/{id}.png",
        "estimatedClaimTime": estimated_claim_time,
        "payoutDisplayType": payout_display_type,
    }


NEW_RECORDS = [
    make_record(
        id="mdi-tdi-wanhua-antitrust-2026",
        title="Wanhua MDI and TDI Antitrust Settlement",
        company="Wanhua Chemical",
        total_amount="$7.75 million",
        individual_payout="Pro rata payment based on eligible direct purchases",
        deadline="2026-10-13",
        category="Consumer",
        eligibility="Individuals and entities that directly purchased qualifying MDI or TDI products in the United States, its territories, or the District of Columbia from January 1, 2016 through July 29, 2026.",
        bullets=[
            "Purchased qualifying MDI or TDI products directly",
            "Purchased from Wanhua or another manufacturer covered by the settlement class",
            "Purchase occurred in the United States, its territories, or D.C. from January 1, 2016 through July 29, 2026",
        ],
        proof_required=True,
        proof_details="A Class Member ID from the settlement notice is required to file the claim. Supporting purchase records may also be required to add or correct purchases in the administrator's records.",
        claim_url="https://forms.ksacms.com/efiling/fr/eform/diisocyanatesantitrustlitigation_claimform/new?form-version=1",
        source_url="https://www.diisocyanatesantitrustlitigation.com/",
        summary="Wanhua agreed to pay $7.75 million to resolve allegations that manufacturers conspired to fix prices and restrict the supply of MDI and TDI. Approved direct purchasers will share the net fund according to their eligible purchases.",
        scope="United States, territories, and District of Columbia",
        case_info="In re Diisocyanates Antitrust Litigation, Misc. No. 18-1001, MDL No. 2862 (W.D. Pa.)",
        status="closingSoon",
        estimated_claim_time="~10 min",
    ),
    make_record(
        id="mdi-tdi-dow-huntsman-antitrust-2026",
        title="Dow and Huntsman MDI and TDI Antitrust Settlements",
        company="The Dow Chemical Company and Huntsman",
        total_amount="$20 million",
        individual_payout="Pro rata payment based on eligible direct purchases",
        deadline="2026-10-19",
        category="Consumer",
        eligibility="Individuals and entities that directly purchased qualifying MDI or TDI products in the United States, its territories, or the District of Columbia from January 1, 2016 through July 29, 2026.",
        bullets=[
            "Purchased qualifying MDI or TDI products directly",
            "Purchased from Dow, Huntsman, or another manufacturer covered by the settlement class",
            "Purchase occurred in the United States, its territories, or D.C. from January 1, 2016 through July 29, 2026",
        ],
        proof_required=True,
        proof_details="A Class Member ID from the settlement notice is required to file the claim. Supporting purchase records may also be required to add or correct purchases in the administrator's records.",
        claim_url="https://forms.ksacms.com/efiling/fr/eform/diisocyanatesantitrustlitigation_claimform/new?form-version=1",
        source_url="https://www.diisocyanatesantitrustlitigation.com/",
        summary="Dow and Huntsman agreed to pay a combined $20 million to resolve allegations concerning price fixing and supply restrictions for MDI and TDI. Approved direct purchasers will receive pro rata payments based on eligible purchases.",
        scope="United States, territories, and District of Columbia",
        case_info="In re Diisocyanates Antitrust Litigation, Misc. No. 18-1001, MDL No. 2862 (W.D. Pa.)",
        estimated_claim_time="~10 min",
    ),
    make_record(
        id="mdi-tdi-basf-covestro-antitrust-2026",
        title="BASF and Covestro MDI and TDI Antitrust Settlements",
        company="BASF and Covestro",
        total_amount="$9.9 million plus a $100,000 notice contribution",
        individual_payout="Pro rata payment based on eligible direct purchases",
        deadline="2026-11-02",
        category="Consumer",
        eligibility="Individuals and entities that directly purchased qualifying MDI or TDI products in the United States, its territories, or the District of Columbia from January 1, 2016 through July 29, 2026.",
        bullets=[
            "Purchased qualifying MDI or TDI products directly",
            "Purchased from BASF, Covestro, or another manufacturer covered by the settlement class",
            "Purchase occurred in the United States, its territories, or D.C. from January 1, 2016 through July 29, 2026",
        ],
        proof_required=True,
        proof_details="A Class Member ID from the settlement notice is required to file the claim. Supporting purchase records may also be required to add or correct purchases in the administrator's records.",
        claim_url="https://forms.ksacms.com/efiling/fr/eform/diisocyanatesantitrustlitigation_claimform/new?form-version=1",
        source_url="https://www.diisocyanatesantitrustlitigation.com/",
        summary="BASF and Covestro agreed to provide $9.9 million for class payments, with BASF contributing another $100,000 toward notice costs, to resolve MDI and TDI antitrust allegations. Approved direct purchasers will receive pro rata payments.",
        scope="United States, territories, and District of Columbia",
        case_info="In re Diisocyanates Antitrust Litigation, Misc. No. 18-1001, MDL No. 2862 (W.D. Pa.)",
        estimated_claim_time="~10 min",
    ),
    make_record(
        id="cpap-medical-data-incident-2026",
        title="CPAP Medical Supplies Data Incident Settlement",
        company="CPAP Medical Supplies and Services",
        total_amount="Cash claims capped at $500,000",
        individual_payout="Up to $5,000 in documented losses plus medical monitoring",
        deadline="2026-11-26",
        category="Data Breach",
        eligibility="United States residents who received notice that the December 2024 CPAP Medical data incident may have affected their private information.",
        bullets=[
            "Reside in the United States",
            "Received notice from CPAP Medical about the December 2024 incident",
            "Private information may have been affected by the incident",
        ],
        proof_required=True,
        proof_details="Cash reimbursement requires records such as receipts, bank statements, or other documentation of losses traceable to the incident. Online filing also requires the Login ID and PIN from the settlement notice.",
        claim_url="https://cpapdataincidentsettlement.com/form/claim",
        source_url="https://cpapdataincidentsettlement.com/",
        summary="CPAP Medical agreed to provide benefits after a December 2024 cyberattack allegedly exposed customer information. Class members may seek up to $5,000 for documented losses and two years of medical identity monitoring.",
        scope="Nationwide",
        case_info="Brett Conner v. CPAP Medical Supplies and Services, Inc., No. CACE-26-011830 (Broward County, Fla.)",
    ),
    make_record(
        id="nyc-doc-strip-search-2026",
        title="New York City DOC Strip Search Settlement",
        company="City of New York and New York City Department of Correction",
        total_amount="$28 million",
        individual_payout="Pro rata payment based on qualifying searches",
        deadline="2026-11-26",
        category="Privacy",
        eligibility="People in New York City Department of Correction custody who received a qualifying repeat strip search at the Manhattan Court Division from March 28, 2020 through February 29, 2024 if classified as Enhanced Security, or from October 1, 2022 through February 29, 2024 for all others.",
        bullets=[
            "Were in New York City DOC custody from March 28, 2020 through February 29, 2024 if classified as Enhanced Security, or from October 1, 2022 through February 29, 2024 otherwise",
            "Were searched at Manhattan Court Division after a search before leaving Rikers Island",
            "Appear on the official settlement class list",
        ],
        proof_required=True,
        proof_details="No receipts or notice ID are requested, but eligibility and the number of qualifying searches must be verified against the official DOC class records using the claimant's identifying information.",
        claim_url="https://veritaconnect.com/NYStripSearchSettlement/",
        source_url="https://www.nystripsearchsettlement.com/",
        summary="New York City agreed to resolve claims that people in DOC custody underwent unnecessary repeat strip searches at the Manhattan Court Division. Approved class members will share a $28 million payment fund based on qualifying searches.",
        scope="New York",
        case_info="Lewis et al. v. City of New York et al., No. 23 Civ. 2600 (CM) (S.D.N.Y.)",
    ),
    make_record(
        id="concora-credit-tcpa-2026",
        title="Concora Credit Prerecorded Call Settlement",
        company="Concora Credit",
        total_amount="$9.375 million",
        individual_payout="$250 to $650 estimated",
        deadline="2026-10-19",
        category="Telemarketing",
        eligibility="People in the United States who received an artificial or prerecorded-voice call from Concora Credit on a cellular telephone from May 2, 2021 through May 31, 2026 when the number was not assigned to a Concora accountholder.",
        bullets=[
            "Received an artificial or prerecorded-voice call on a cellular telephone",
            "Call occurred from May 2, 2021 through May 31, 2026",
            "Telephone number was not assigned to a Concora accountholder",
        ],
        proof_required=True,
        proof_details="Notice recipients must use their personalized claim credentials. A person without a notice must request a form and provide evidence that a qualifying prerecorded call reached their cellular telephone.",
        claim_url="https://www.sealstcpasettlement.com/",
        source_url="https://www.sealstcpasettlement.com/",
        summary="Concora Credit agreed to settle allegations that it placed prerecorded calls to cellular numbers belonging to noncustomers. Approved claimants will share the net settlement fund equally, with payments estimated at $250 to $650.",
        scope="Nationwide",
        case_info="Seals v. Concora Credit Inc., No. 3:25-cv-00728-AN (D. Or.)",
    ),
    make_record(
        id="fujifilm-diosynth-data-2026",
        title="Fujifilm Diosynth Data Incident Settlement",
        company="Fujifilm Diosynth Biotechnologies U.S.A.",
        total_amount="Out-of-pocket claims capped at $175,000",
        individual_payout="$50 cash or up to $2,500 in documented losses plus monitoring",
        deadline="2026-11-25",
        category="Data Breach",
        eligibility="People who received notice that the 2025 Fujifilm Diosynth data incident may have affected their private information.",
        bullets=[
            "Received notice from Fujifilm Diosynth",
            "Private information may have been affected by the 2025 incident",
            "Submit a valid claim by November 25, 2026",
        ],
        proof_required=True,
        proof_details="The standard online claim process requires the Login ID and PIN from the settlement notice. The $2,500 loss tier also requires reasonable supporting documentation; the $50 alternative does not require proof of loss.",
        claim_url="https://www.flbdatasettlement.com/form/claim",
        source_url="https://www.flbdatasettlement.com/",
        summary="Fujifilm Diosynth agreed to provide benefits after a 2025 data incident allegedly exposed private information. Class members may request $50 cash or documented losses up to $2,500 and may also receive two years of credit monitoring.",
        scope="Nationwide",
        case_info="Johnson et al. v. Fujifilm Diosynth Biotechnologies U.S.A., Inc., No. 26CV012339-910 (Wake County Superior Court, N.C.)",
    ),
    make_record(
        id="la-jolla-group-data-2026",
        title="La Jolla Group Employee Data Settlement",
        company="La Jolla Group",
        total_amount="Settlement amount not disclosed",
        individual_payout="$45 or $95 cash, or up to $2,100 in losses and time, plus monitoring",
        deadline="2026-11-23",
        category="Data Breach",
        eligibility="Current and former La Jolla Group employees in the United States whose personal information was affected by the November 2023 cybersecurity incident.",
        bullets=[
            "Are a current or former La Jolla Group employee",
            "Reside in the United States",
            "Personal information was affected by the November 2023 incident",
        ],
        proof_required=True,
        proof_details="The official claim form requires the Class Member ID and PIN from the settlement notice. Documented-loss claims also require third-party records; alternative cash is $95 for California residents and $45 for other class members.",
        claim_url="https://www.ljgdatasettlement.com/form/claim",
        source_url="https://www.ljgdatasettlement.com/",
        summary="La Jolla Group agreed to settle claims arising from a November 2023 employee data incident. Class members may choose alternative cash or seek up to $2,000 in documented losses and $100 for lost time, and may request monitoring.",
        scope="Nationwide",
        case_info="Dempsey et al. v. La Jolla Group Inc., No. 30-2024-01416569-CU-MC-CXC (Orange County Superior Court, Calif.)",
    ),
    make_record(
        id="schnucks-rewards-tax-2026",
        title="Schnucks Rewards Sales Tax Settlement",
        company="Schnuck Markets",
        total_amount="Up to $6.3 million in claimant payments",
        individual_payout="$7",
        deadline="2026-11-03",
        category="Consumer",
        eligibility="Current or former Schnucks Rewards members who redeemed points on tax-eligible personal, family, or household purchases at Missouri Schnucks stores from May 2, 2020 through August 7, 2026.",
        bullets=[
            "Are or were a Schnucks Rewards member",
            "Redeemed points on tax-eligible personal, family, or household purchases",
            "Purchase occurred at a Missouri Schnucks store from May 2, 2020 through August 7, 2026",
        ],
        proof_required=True,
        proof_details="Online filing requires the Access Code and PIN from the postcard notice. A paper route is available for people without the postcard, but account information is required and eligibility is verified against Schnucks Rewards records.",
        claim_url="https://schnuckstaxsettlement.com/Claim-Form/PageControl/Authentication",
        source_url="https://www.schnuckstaxsettlement.com/",
        summary="Schnucks agreed to settle allegations that Missouri sales tax was calculated before Rewards-point discounts were applied. Approved class members will receive a $7 payment, and Schnucks will change its point-of-sale calculations.",
        scope="Missouri",
        case_info="Garcia v. Schnuck Market, Inc., No. 25SL-CC04761 (St. Louis County Circuit Court, Mo.)",
        payout_display_type="exact",
    ),
    make_record(
        id="vasindas-data-2026",
        title="Vasindas Around the Clock Care Data Settlement",
        company="Vasindas' Around the Clock Care",
        total_amount="Settlement amount not disclosed",
        individual_payout="$70 cash or up to $2,500 in documented losses plus monitoring",
        deadline="2026-11-23",
        category="Data Breach",
        eligibility="United States residents whose personal information was potentially affected by the Around the Clock Care incident that occurred from January 30 through June 18, 2024.",
        bullets=[
            "Reside in the United States",
            "Personal information was potentially affected by the incident",
            "Incident occurred from January 30 through June 18, 2024",
        ],
        proof_required=True,
        proof_details="The standard online process requires the Login ID and PIN from the notice. The $2,500 loss tier requires supporting records; the $70 alternative cash option does not require proof of loss.",
        claim_url="https://www.vasindasdatasettlement.com/form/claim",
        source_url="https://www.vasindasdatasettlement.com/",
        summary="Vasindas' Around the Clock Care agreed to provide benefits after a 2024 cyberattack allegedly exposed personal and medical information. Class members may choose $70 cash or documented losses up to $2,500 and monitoring.",
        scope="Nationwide",
        case_info="Nelson et al. v. Vasindas' Around the Clock Care Inc., No. BCV-24-102900 (Kern County Superior Court, Calif.)",
    ),
    make_record(
        id="autobell-data-2026",
        title="Autobell Car Wash Data Incident Settlement",
        company="Autobell Car Wash",
        total_amount="Settlement amount not disclosed",
        individual_payout="$45 cash or up to $5,000 in documented losses plus monitoring",
        deadline="2026-11-12",
        category="Data Breach",
        eligibility="United States residents who received notice that Autobell's April 2024 data incident affected their personal information.",
        bullets=[
            "Reside in the United States",
            "Received an Autobell data incident notice",
            "Personal information was affected by the April 2024 incident",
        ],
        proof_required=True,
        proof_details="The standard online process requires the Unique ID and PIN from the notice. The loss tier requires supporting records; the $45 alternative cash option does not require proof of loss.",
        claim_url="https://www.autobelldatasettlement.com/",
        source_url="https://www.autobelldatasettlement.com/",
        summary="Autobell agreed to provide benefits after an April 2024 cyberattack allegedly exposed personal information. Class members may choose $45 cash or seek documented losses up to $5,000 and may receive monitoring.",
        scope="Nationwide",
        case_info="Pauken v. Autobell Car Wash LLC, No. 26CV006404-590 (Mecklenburg County Superior Court, N.C.)",
    ),
    make_record(
        id="carter-credit-union-data-2026",
        title="Carter Credit Union Data Incident Settlement",
        company="Carter Credit Union",
        total_amount="Settlement amount not disclosed",
        individual_payout="$50 cash or up to $2,500 in documented losses plus monitoring",
        deadline="2026-11-19",
        category="Data Breach",
        eligibility="People whose personally identifiable information was compromised in the Carter Credit Union data incident that began on or about June 25, 2025.",
        bullets=[
            "Personal information was compromised",
            "Incident began on or about June 25, 2025",
            "Submit a valid claim by November 19, 2026",
        ],
        proof_required=True,
        proof_details="The standard online process requires the Login ID and PIN from the notice. The $2,500 loss tier requires supporting records; the $50 alternative cash option does not require proof of loss.",
        claim_url="https://www.ccudatasettlement.com/form/claim",
        source_url="https://www.ccudatasettlement.com/",
        summary="Carter Credit Union agreed to provide benefits after a June 2025 cyberattack allegedly exposed customer information. Class members may choose $50 cash or seek documented losses up to $2,500 and monitoring.",
        scope="Nationwide",
        case_info="Ellis et al. v. Carter Credit Union d/b/a Carter Federal Credit Union, No. 662980-C (1st Judicial District Court, Caddo Parish, La.)",
    ),
    make_record(
        id="southern-graphics-data-2026",
        title="Southern Graphics Data Incident Settlement",
        company="Southern Graphics",
        total_amount="$750,000",
        individual_payout="Pro rata cash or up to $3,500 in documented losses plus monitoring",
        deadline="2026-11-03",
        category="Data Breach",
        eligibility="People who received notice that the December 2024 Southern Graphics data incident may have compromised their private information.",
        bullets=[
            "Received notice from Southern Graphics",
            "Private information may have been compromised",
            "Incident occurred in December 2024",
        ],
        proof_required=True,
        proof_details="The standard online process requires the Login ID and PIN from the notice. Documented-loss claims require supporting records; the alternative pro rata cash option does not require proof of loss.",
        claim_url="https://southerngraphicsdatasettlement.com/form/claim",
        source_url="https://southerngraphicsdatasettlement.com/",
        summary="Southern Graphics agreed to a $750,000 settlement after a December 2024 cyberattack allegedly exposed employee and family information. Class members may choose pro rata cash or seek up to $3,500 in documented losses and monitoring.",
        scope="Nationwide",
        case_info="Davis et al. v. Southern Graphics Inc., No. 3:25-cv-00563 (W.D. Ky.)",
    ),
    make_record(
        id="twist-bioscience-securities-2026",
        title="Twist Bioscience Securities Settlement",
        company="Twist Bioscience",
        total_amount="$17.05 million",
        individual_payout="$0.31 per eligible share estimated before deductions",
        deadline="2026-11-17",
        category="Financial",
        eligibility="People and entities that acquired Twist Bioscience common stock in the December 2020 offering or from December 20, 2018 through November 15, 2022 and suffered a recognized loss.",
        bullets=[
            "Acquired Twist common stock in the December 2020 offering or during the class period",
            "Class period ran from December 20, 2018 through November 15, 2022",
            "Suffered a loss recognized under the settlement plan",
        ],
        proof_required=True,
        proof_details="Claimants must provide broker confirmations, account statements, or other records showing Twist stock purchases, sales, and holdings.",
        claim_url="https://www.twistsecuritiessettlement.com/form/securities-claim",
        source_url="https://www.twistsecuritiessettlement.com/",
        summary="Twist Bioscience and certain executives agreed to settle claims concerning alleged misstatements about production, product quality, and accounting. Approved investors will receive pro rata payments under the plan of allocation.",
        scope="Nationwide",
        case_info="Peters v. Twist Bioscience Corp. et al., No. 5:22-cv-08168-EKL (N.D. Cal.)",
        estimated_claim_time="~10 min",
    ),
    make_record(
        id="covenant-transport-job-posting-2026",
        title="Covenant Transport Washington Job Applicant Settlement",
        company="Covenant Transport",
        total_amount="$288,125 to $412,500",
        individual_payout="$920.91 to $5,000 estimated",
        deadline="2026-11-09",
        category="Employment",
        eligibility="People who applied online for a Covenant Transport team-driver position located in Washington from January 1, 2023 through June 17, 2024.",
        bullets=[
            "Applied online to Covenant Transport",
            "Applied for a team-driver position located in Washington",
            "Applied from January 1, 2023 through June 17, 2024",
        ],
        proof_required=True,
        proof_details="Eligibility is verified against Covenant's job-application records. The online process may use personalized CPT credentials; the paper form requires identifying and application information.",
        claim_url="https://www.covenanttransportsettlement.com/",
        source_url="https://www.covenanttransportsettlement.com/",
        summary="Covenant Transport agreed to settle allegations that Washington team-driver job postings omitted wage ranges and benefit information. Approved applicants will receive equal pro rata shares, subject to the settlement cap.",
        scope="Washington State",
        case_info="Pierre et al. v. Covenant Transport Inc., No. 24-2-13005-5 SEA (King County Superior Court, Wash.)",
    ),
    make_record(
        id="wayne-memorial-hospital-data-2026",
        title="Wayne Memorial Hospital Data Incident Settlement",
        company="Wayne Memorial Hospital",
        total_amount="Alternative cash payments capped at $300,000",
        individual_payout="$25 estimated or up to $5,000 in documented losses plus monitoring",
        deadline="2026-12-07",
        category="Data Breach",
        eligibility="People whose personal information was potentially compromised in the Wayne Memorial Hospital data incident that occurred from May 30 through June 3, 2024.",
        bullets=[
            "Personal information was potentially compromised",
            "Incident occurred from May 30 through June 3, 2024",
            "Received or qualify for the Wayne Memorial incident notice",
        ],
        proof_required=True,
        proof_details="A Unique ID from the settlement notice is required for every cash claim, and online claimants also need the notice passcode. The $5,000 loss tier requires supporting documentation.",
        claim_url="https://www.wmhdatasettlement.com/",
        source_url="https://www.wmhdatasettlement.com/",
        summary="Wayne Memorial Hospital agreed to provide benefits after a 2024 cyberattack allegedly exposed private information. Class members may request estimated $25 alternative cash or documented losses up to $5,000 and monitoring.",
        scope="Nationwide",
        case_info="Bates et al. v. Wayne Memorial Hospital Auxiliary Inc. d/b/a Wayne Memorial Hospital, No. SUCV2025000239 (Wayne County Superior Court, Ga.)",
    ),
    make_record(
        id="highland-health-systems-data-2026",
        title="Highland Health Systems Data Breach Settlement",
        company="Highland Health Systems",
        total_amount="$650,000",
        individual_payout="$85 estimated cash or up to $5,000 in documented losses plus monitoring",
        deadline="2026-10-28",
        category="Data Breach",
        eligibility="United States residents whose private information was exposed to unauthorized parties in the Highland Health Systems data breach discovered on or about July 3, 2023.",
        bullets=[
            "Reside in the United States",
            "Private information was exposed in the Highland Health breach",
            "Breach was discovered on or about July 3, 2023",
        ],
        proof_required=False,
        proof_details="The official site provides a claim form that can be filed without a Login ID or PIN. The estimated $85 alternative cash option requires no supporting documents; only the separate $5,000 loss tier requires records.",
        claim_url="https://highlanddatabreachsettlement.com/form/open",
        source_url="https://highlanddatabreachsettlement.com/",
        summary="Highland Health Systems agreed to a $650,000 settlement after a 2023 cyberattack allegedly exposed personal and medical information. Class members may choose estimated $85 cash or documented losses up to $5,000 and monitoring.",
        scope="Nationwide",
        case_info="Weyerman et al. v. Highland Health Systems et al., No. 2024-CV-900370 (Calhoun County Circuit Court, Ala.)",
    ),
    make_record(
        id="amn-healthcare-cipa-2026",
        title="AMN Healthcare Interpretation Recording Settlement",
        company="AMN Healthcare",
        total_amount="$4.5 million",
        individual_payout="Pro rata payment up to $10,000",
        deadline="2026-10-27",
        category="Privacy",
        eligibility="People physically present in California who participated in an AMN-interpreted conversation from December 4, 2022 through August 7, 2026 that AMN allegedly monitored, listened to, or recorded without prior consent.",
        bullets=[
            "Were physically present in California",
            "Participated in an AMN-interpreted conversation from December 4, 2022 through August 7, 2026",
            "Conversation was allegedly monitored, listened to, or recorded without prior consent",
        ],
        proof_required=True,
        proof_details="Claimants must provide details sufficient to identify the interpreted session and certify eligibility. A no-ID registration route exists, but the claim is verified against AMN's session records.",
        claim_url="https://forms.ksacms.com/efiling/fr/register/carrero_v_amnhealthcare_register/new?form-version=1",
        source_url="https://amncipasettlement.com/",
        summary="AMN Healthcare agreed to settle allegations that California interpretation sessions were monitored or recorded without prior consent. Approved claimants will share the net $4.5 million fund pro rata, capped at $10,000 each.",
        scope="California",
        case_info="Carrero et al. v. AMN Healthcare Inc. et al., No. 37-2023-00052448-CU-NP-CTL (San Diego Superior Court, Calif.)",
    ),
    make_record(
        id="international-shoppes-data-2026",
        title="International Shoppes Data Incident Settlement",
        company="International Shoppes and Diplomatic Duty Free Shops of New York",
        total_amount="$500,000 benefit cap",
        individual_payout="$50 cash or up to $4,000 in documented losses plus monitoring",
        deadline="2026-11-11",
        category="Data Breach",
        eligibility="People whose personal information was compromised in the November 2023 data incident involving International Shoppes or Diplomatic Duty Free Shops of New York.",
        bullets=[
            "Personal information was compromised",
            "Incident occurred in November 2023",
            "Affected by International Shoppes or Diplomatic Duty Free Shops of New York",
        ],
        proof_required=True,
        proof_details="The standard online process requires the Login ID and PIN from the notice. The $4,000 loss tier requires documentation; the $50 alternative cash option does not require proof of loss.",
        claim_url="https://www.ishoppesdatasettlement.com/form/claim",
        source_url="https://www.ishoppesdatasettlement.com/",
        summary="International Shoppes and Diplomatic Duty Free Shops agreed to provide benefits after a November 2023 cyberattack allegedly exposed personal information. Class members may choose $50 cash or documented losses up to $4,000 and monitoring.",
        scope="Nationwide",
        case_info="Lazar and Khan v. International Shoppes LLC et al., Index No. 623891/2025 (Nassau County Supreme Court, N.Y.)",
    ),
    make_record(
        id="high5-games-washington-2026",
        title="High 5 Games Washington Coin Purchase Settlement",
        company="High 5 Games",
        total_amount="$12 million to $30 million",
        individual_payout="Pro rata payment based on qualifying virtual-coin purchases",
        deadline="2026-11-13",
        category="Consumer",
        eligibility="People who purchased virtual coins in High 5 Casino or High 5 Vegas in or associated with Washington from April 9, 2014 through September 30, 2022.",
        bullets=[
            "Purchased virtual coins in High 5 Casino or High 5 Vegas",
            "Purchase was made in or associated with Washington",
            "Purchase occurred from April 9, 2014 through September 30, 2022",
        ],
        proof_required=True,
        proof_details="The Unique ID may be skipped and receipts are not requested, but eligibility and the award are determined from the claimant's High 5 account and virtual-coin purchase records.",
        claim_url="https://www.high5lawsuit.com/",
        source_url="https://www.high5lawsuit.com/",
        summary="High 5 Games agreed to resolve Washington gambling-loss claims involving virtual-coin purchases. Approved claimants will receive shares of a settlement funded over multiple years and allocated according to qualifying purchases.",
        scope="Washington State",
        case_info="Larsen v. PTT LLC d/b/a High 5 Games LLC et al., No. 3:18-cv-05275-TMC (W.D. Wash.)",
    ),
    make_record(
        id="sugared-bronzed-tcpa-2026",
        title="Sugared + Bronzed Text Message Settlement",
        company="Sugared + Bronzed",
        total_amount="$750,000",
        individual_payout="$110 to $222 estimated",
        deadline="2026-10-02",
        category="Telemarketing",
        eligibility="People whose mobile number received two or more Sugared + Bronzed telemarketing texts through Klaviyo within a 12-month period after an opt-out request from August 14, 2020 through July 17, 2026.",
        bullets=[
            "Received two or more Sugared + Bronzed telemarketing texts within 12 months",
            "Texts arrived after an opt-out or stop request",
            "Texts occurred from August 14, 2020 through July 17, 2026",
        ],
        proof_required=True,
        proof_details="The claim site permits filing without a Login ID or PIN, but the submitted mobile number must match Sugared + Bronzed and Klaviyo records showing the qualifying messages and stop request.",
        claim_url="https://www.sbtcpasettlement.com/form/open",
        source_url="https://sbtcpasettlement.com/",
        summary="Sugared + Bronzed agreed to settle allegations that it sent telemarketing texts after recipients asked it to stop. Approved claimants will share the net $750,000 fund, with payments estimated at $110 to $222.",
        scope="Nationwide",
        case_info="Grippo v. Sugared + Bronzed LLC, No. 8:24-cv-01792-AB-DFM (C.D. Cal.)",
        status="closingSoon",
        estimated_claim_time="~3 min",
    ),
    make_record(
        id="levoit-air-purifier-2026",
        title="Levoit Air Purifier Marketing Settlement",
        company="VeSync and Levoit",
        total_amount="Up to $15 million in claimant benefits",
        individual_payout="$10",
        deadline="2026-11-03",
        category="Product",
        eligibility="People who purchased a qualifying Levoit Core or EverestAir air purifier or replacement filter in the United States with True HEPA, HEPA, or H13 language from August 29, 2019 through August 4, 2023.",
        bullets=[
            "Purchased a qualifying Levoit Core or EverestAir purifier or replacement filter",
            "Product used True HEPA, HEPA, or H13 marketing language",
            "Purchased in the United States from August 29, 2019 through August 4, 2023",
        ],
        proof_required=True,
        proof_details="The claim requires proof of the original qualifying purchase date. Approved claims receive a $10 digital payment.",
        claim_url="https://lapsettlement.com/",
        source_url="https://lapsettlement.com/",
        summary="VeSync agreed to settle allegations concerning HEPA-related marketing for certain Levoit air purifiers and filters. Eligible purchasers who substantiate a qualifying original purchase may request a $10 digital payment.",
        scope="Nationwide",
        case_info="Sen et al. v. VeSync (US) Corp., Index No. 510627/2026 (Kings County Supreme Court, N.Y.)",
        payout_display_type="exact",
    ),
    make_record(
        id="wpm-salina-data-2026",
        title="WPM Pathology and Salina Regional Data Settlement",
        company="WPM Pathology Laboratory and Salina Regional Health Center",
        total_amount="Settlement amount not disclosed",
        individual_payout="$45 cash or up to $4,480 in losses and time plus monitoring",
        deadline="2026-10-19",
        category="Data Breach",
        eligibility="People whose private information was compromised in the November 2024 incident involving WPM Pathology Laboratory or Salina Regional Health Center, including people directly notified by the defendants.",
        bullets=[
            "Private information was compromised",
            "Incident occurred in November 2024",
            "Affected by WPM Pathology Laboratory or Salina Regional Health Center",
        ],
        proof_required=True,
        proof_details="The standard online process requires the Notice ID and PIN. Loss claims require supporting documentation and lost-time claims require a description; the $45 alternative cash option does not require proof of loss.",
        claim_url="https://www.wpmpldatabreach.com/",
        source_url="https://www.wpmpldatabreach.com/",
        summary="WPM Pathology Laboratory and Salina Regional Health Center agreed to provide benefits after a November 2024 cyberattack allegedly exposed patient information. Class members may choose $45 cash or seek losses and time up to $4,480 and monitoring.",
        scope="Nationwide",
        case_info="Steinle v. WPM Pathology Laboratory and Salina Regional Health Center Inc., No. SA-2025-CV-000218 (Saline County District Court, Kan.)",
    ),
    make_record(
        id="onetouchpoint-data-2026",
        title="OneTouchPoint Data Incident Settlement",
        company="OneTouchPoint",
        total_amount="Settlement amount not disclosed",
        individual_payout="$75 cash or up to $5,600 in losses and time plus monitoring",
        deadline="2026-11-16",
        category="Data Breach",
        eligibility="People in the United States whose private information OneTouchPoint's investigation determined was affected by the April 2022 data incident.",
        bullets=[
            "Reside in the United States",
            "Private information was determined to be affected",
            "Incident occurred in April 2022",
        ],
        proof_required=True,
        proof_details="The standard online process requires the Claim Number and PIN from the notice. Loss claims require documentation and lost-time claims require a description; the $75 alternative cash option does not require proof of loss.",
        claim_url="https://otpdataincident.com/",
        source_url="https://otpdataincident.com/",
        summary="OneTouchPoint agreed to provide benefits after an April 2022 data incident allegedly exposed private information. Monetary-class members may choose $75 cash or seek up to $5,600 in combined losses and time and monitoring.",
        scope="Nationwide",
        case_info="Dusterhoft v. OneTouchPoint Corp., No. 2025CV002181 (Waukesha County Circuit Court, Wis.)",
    ),
    make_record(
        id="peco-foods-data-2026",
        title="Peco Foods Data Incident Settlement",
        company="Peco Foods",
        total_amount="$950,000",
        individual_payout="Up to $550 residual cash or up to $6,550 in combined benefits plus monitoring",
        deadline="2026-11-09",
        category="Data Breach",
        eligibility="United States residents who received written notice that their personally identifiable information may have been compromised in the Peco Foods data incident on or around December 4, 2023.",
        bullets=[
            "Reside in the United States",
            "Received written notice from Peco Foods",
            "Information may have been compromised on or around December 4, 2023",
        ],
        proof_required=True,
        proof_details="The standard online process requires the Claim ID from the settlement notice. Ordinary and extraordinary losses require documentation, and lost time requires a description; residual cash does not require proof of loss.",
        claim_url="https://www.pecofoodsdatasettlement.com/",
        source_url="https://www.pecofoodsdatasettlement.com/",
        summary="Peco Foods agreed to a $950,000 settlement after a December 2023 data incident allegedly exposed personal information. Class members may request residual cash, documented ordinary and extraordinary losses, lost time, and monitoring.",
        scope="Nationwide",
        case_info="Ryan et al. v. Peco Foods Inc., No. 63-CV-2025-900067 (Tuscaloosa County Circuit Court, Ala.)",
    ),
    make_record(
        id="regional-urology-data-2026",
        title="Regional Urology and Ochsner LSU Data Settlement",
        company="Regional Urology and Ochsner LSU Health",
        total_amount="Settlement amount not disclosed",
        individual_payout="$40 cash or up to $5,000 in documented losses plus monitoring",
        deadline="2026-11-16",
        category="Data Breach",
        eligibility="United States residents whose private information was potentially compromised in the October 2025 data incident involving Regional Urology and Ochsner LSU Health.",
        bullets=[
            "Reside in the United States",
            "Private information was potentially compromised",
            "Incident involved Regional Urology and Ochsner LSU Health in October 2025",
        ],
        proof_required=True,
        proof_details="The standard online process requires the Login ID and PIN from the notice. The $5,000 loss tier requires supporting documentation; the $40 alternative cash option does not require proof of loss.",
        claim_url="https://www.regionalurologydatasettlement.com/",
        source_url="https://www.regionalurologydatasettlement.com/",
        summary="Regional Urology and Ochsner LSU Health agreed to provide benefits after an October 2025 cyberattack allegedly exposed personal and medical information. Class members may choose $40 cash or documented losses up to $5,000 and monitoring.",
        scope="Nationwide",
        case_info="Clark et al. v. Regional Urology LLC et al., No. 662345 (1st Judicial District Court, Caddo Parish, La.)",
    ),
    make_record(
        id="mental-health-association-data-2026",
        title="Mental Health Association Data Breach Settlement",
        company="Mental Health Association",
        total_amount="$300,000 benefit cap",
        individual_payout="$40 cash or up to $5,075 in losses and time plus monitoring",
        deadline="2026-11-19",
        category="Data Breach",
        eligibility="People whose private information was accessible during the November 2024 cyberattack on Mental Health Association, including identified people who received notice.",
        bullets=[
            "Private information was accessible during the incident",
            "Incident occurred in November 2024",
            "Included in Mental Health Association's affected records",
        ],
        proof_required=True,
        proof_details="The standard online process requires the Login ID and PIN from the notice. Documented losses require records and lost time requires a description; the $40 alternative cash option does not require proof of loss.",
        claim_url="https://mhadatasettlement.com/",
        source_url="https://mhadatasettlement.com/",
        summary="Mental Health Association agreed to provide benefits after a November 2024 cyberattack allegedly exposed personal and medical information. Class members may choose $40 cash or seek up to $5,075 in losses and time and monitoring.",
        scope="Nationwide",
        case_info="Campbell et al. v. Mental Health Association Inc., No. 2579CV00419 (Hampden Superior Court, Mass.)",
    ),
    make_record(
        id="california-casualty-data-2026",
        title="California Casualty Data Incident Settlement",
        company="California Casualty",
        total_amount="Settlement amount not disclosed",
        individual_payout="$50 cash or up to $4,000 in documented losses plus monitoring",
        deadline="2026-11-16",
        category="Data Breach",
        eligibility="United States residents whose personally identifiable information was affected by the California Casualty data incident discovered in September 2025.",
        bullets=[
            "Reside in the United States",
            "Personally identifiable information was affected",
            "Incident was discovered in September 2025",
        ],
        proof_required=True,
        proof_details="The standard online process requires the Login ID and PIN from the settlement notice. The $4,000 loss tier requires supporting documentation; the $50 alternative cash option does not require proof of loss.",
        claim_url="https://cacasualtydatasettlement.com/form/claim/",
        source_url="https://cacasualtydatasettlement.com/",
        summary="California Casualty agreed to provide benefits after a September 2025 cyberattack allegedly exposed personal information. Class members may choose $50 cash or seek documented losses up to $4,000 and monitoring.",
        scope="Nationwide",
        case_info="Amin et al. v. California Casualty Indemnity Exchange d/b/a California Casualty Group, No. STK-CV-UBT-2026-0003331 (San Joaquin County Superior Court, Calif.)",
    ),
    make_record(
        id="furniture-mart-usa-data-2026",
        title="Furniture Mart USA Data Breach Settlement",
        company="Furniture Mart USA",
        total_amount="Settlement amount not disclosed",
        individual_payout="$75 cash or up to $4,600 in losses and time plus monitoring",
        deadline="2026-11-03",
        category="Data Breach",
        eligibility="United States residents whose personal information was potentially compromised in the November 2024 Furniture Mart USA data breach.",
        bullets=[
            "Reside in the United States",
            "Personal information was potentially compromised",
            "Incident occurred in November 2024",
        ],
        proof_required=True,
        proof_details="The standard online process requires the Login ID and PIN from the notice. Loss claims require supporting records and lost time requires a description; the $75 alternative cash option does not require proof of loss.",
        claim_url="https://www.fmusadatabreachsettlement.com/",
        source_url="https://www.fmusadatabreachsettlement.com/",
        summary="Furniture Mart USA agreed to provide benefits after a November 2024 cyberattack allegedly exposed personal information. Class members may choose $75 cash or seek up to $4,600 in losses and time and monitoring.",
        scope="Nationwide",
        case_info="In re Furniture Mart USA Inc. Data Breach Litigation, No. 4:25-cv-04018-RAL (D.S.D.)",
    ),
    make_record(
        id="summit-medical-data-2026",
        title="Summit Medical Group Data Incident Settlement",
        company="Summit Medical Group",
        total_amount="$500,000 cash-payment cap",
        individual_payout="Up to $45 for lost time and up to $2,500 in documented losses plus monitoring",
        deadline="2026-11-04",
        category="Data Breach",
        eligibility="Living United States residents whose private information was potentially compromised in the September 2024 cyberattack on Summit Medical Group.",
        bullets=[
            "Are a living resident of the United States",
            "Private information was potentially compromised",
            "Incident occurred in September 2024",
        ],
        proof_required=True,
        proof_details="The standard online process requires the Login ID and PIN from the notice. The $2,500 loss tier requires documents; the separate lost-time tier requires an attestation and description and is capped at $45.",
        claim_url="https://summitmedicaldatasettlement.com/form/claim",
        source_url="https://summitmedicaldatasettlement.com/",
        summary="Summit Medical Group agreed to provide benefits after a September 2024 cyberattack allegedly exposed patient information. Class members may seek documented losses up to $2,500, up to $45 for attested lost time, and medical monitoring.",
        scope="Nationwide",
        case_info="Harris et al. v. Summit Medical Group PLLC, No. 2-119-25 (Knox County Circuit Court, Tenn.)",
    ),
    make_record(
        id="raging-waters-fee-2026",
        title="Raging Waters Processing Fee Settlement",
        company="Festival Fun Parks and Raging Waters",
        total_amount="$850,000",
        individual_payout="Pro rata payment based on processing fees paid",
        deadline="2026-11-24",
        category="Consumer",
        eligibility="United States residents who bought admission tickets from RagingWaters.com from June 1, 2020 through June 22, 2026 and paid a processing fee.",
        bullets=[
            "Reside in the United States",
            "Purchased admission tickets from RagingWaters.com",
            "Paid a processing fee from June 1, 2020 through June 22, 2026",
        ],
        proof_required=True,
        proof_details="The standard online process requires the ID and confirmation code from the settlement notice. Claimants must attest that they made a qualifying purchase and paid a processing fee; payment is checked against available transaction records.",
        claim_url="https://www.ragingwaterssettlement.com/",
        source_url="https://www.ragingwaterssettlement.com/",
        summary="Festival Fun Parks agreed to settle allegations that mandatory Raging Waters processing fees were inadequately disclosed during online checkout. Approved claimants will share the net $850,000 fund based on fees paid.",
        scope="Nationwide",
        case_info="Velazquez v. Festival Fun Parks LLC, No. 24STCV20667 (Los Angeles County Superior Court, Calif.)",
        estimated_claim_time="~3 min",
    ),
    make_record(
        id="mortgage-investors-group-data-2026",
        title="Mortgage Investors Group Data Incident Settlement",
        company="Mortgage Investors Group",
        total_amount="$925,000 benefit cap",
        individual_payout="$45 cash or up to $2,000 in documented losses plus monitoring",
        deadline="2026-11-19",
        category="Data Breach",
        eligibility="People whose sensitive information was potentially exposed in the December 2024 Mortgage Investors Group data incident.",
        bullets=[
            "Sensitive information was potentially exposed",
            "Incident occurred in December 2024",
            "Included in Mortgage Investors Group's affected records",
        ],
        proof_required=True,
        proof_details="The standard online process requires the Login ID and PIN from the settlement notice. The $2,000 loss tier requires supporting documentation; the $45 alternative cash option does not require proof of loss.",
        claim_url="https://www.migdatasettlement.com/",
        source_url="https://www.migdatasettlement.com/",
        summary="Mortgage Investors Group agreed to provide benefits after a December 2024 cyberattack allegedly exposed customer information. Class members may choose $45 cash or seek documented losses up to $2,000 and monitoring.",
        scope="Nationwide",
        case_info="White v. Mortgage Investors Group Inc., No. 25-0350-III (Davidson County Chancery Court, Tenn.)",
    ),
]


def main() -> None:
    records = json.loads(FEED.read_text())
    existing_ids = {record["id"] for record in records}
    duplicate_inputs = sorted(
        record["id"] for record in NEW_RECORDS if record["id"] in existing_ids
    )
    if duplicate_inputs:
        print(f"Already present; no changes made: {', '.join(duplicate_inputs)}")
        return

    records.extend(NEW_RECORDS)
    FEED.write_text(json.dumps(records, ensure_ascii=False, indent=2) + "\n")
    print(f"Added {len(NEW_RECORDS)} records; feed now has {len(records)} records")


if __name__ == "__main__":
    main()
