#!/usr/bin/env python3
"""Add the settlements verified on 2026-08-19 to the English source feed.

The script is intentionally idempotent so the reviewed records can be reapplied without
creating duplicates. Localized feeds are generated separately from settlements.json.
"""

from __future__ import annotations

import json
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
FEED = ROOT / "settlements.json"
IMAGE_ROOT = "https://raw.githubusercontent.com/Andrewegao/x9k2m4-static/main/images"


def favicon(domain: str) -> str:
    return f"https://www.google.com/s2/favicons?sz=128&domain={domain}"


def image(name: str) -> str:
    return f"{IMAGE_ROOT}/{name}"


NEW_RECORDS = [
    {
        "id": "advanced-recovery-equipment-data-breach-2026",
        "title": "Advanced Recovery Equipment Data Breach Settlement",
        "company": "Advanced Recovery Equipment & Supplies",
        "imageURL": image("data-breach-generic-1.jpg"),
        "totalAmount": "Cash payments capped at $325,000",
        "individualPayout": "Up to $4,250 in documented losses, up to $50 cash, and monitoring",
        "deadline": "2026-08-24",
        "category": "Data Breach",
        "eligibility": "United States residents whose personally identifiable information was compromised in the Advanced Recovery Equipment & Supplies data incident announced in or around October 2024.",
        "eligibilityBullets": [
            "Reside in the United States",
            "Personally identifiable information was compromised in the incident",
            "Incident was announced in or around October 2024",
        ],
        "proofRequired": True,
        "proofDetails": "The online and paper forms require the unique login and password printed on the notice. Ordinary and extraordinary loss claims also require supporting records; the cash payment and monitoring options do not require proof of loss.",
        "claimURL": "https://www.advancedrecoverydatasettlement.com/claims_filing.html",
        "sourceURL": "https://www.advancedrecoverydatasettlement.com/",
        "summary": "Advanced Recovery Equipment & Supplies agreed to provide benefits after a data incident allegedly exposed personal information. Eligible class members may seek up to $750 for documented ordinary losses, up to $3,500 for documented extraordinary losses, a cash payment of up to $50, and two years of one-bureau credit monitoring. Cash payments are subject to a $325,000 aggregate cap.",
        "scope": "Nationwide",
        "caseInfo": "Edri, et al. v. Advanced Recovery Equipment & Supplies, LLC, No. 529489/2024 (New York Supreme Court, Kings County); administrator RG/2 Claims Administration",
        "dateAdded": "2026-08-19",
        "status": "open",
        "claimCount": None,
        "logoURL": favicon("advancedrecoveryequipment.com"),
        "estimatedClaimTime": "~5 min",
        "payoutDisplayType": "details",
    },
    {
        "id": "aidvantage-tcpa-settlement-2026",
        "title": "Aidvantage Prerecorded-Call Settlement",
        "company": "Aidvantage",
        "imageURL": image("phone-call-generic.jpg"),
        "totalAmount": "$3 million",
        "individualPayout": "Pro rata cash payment",
        "deadline": "2026-08-24",
        "category": "Telemarketing",
        "eligibility": "People who did not have an account serviced by Aidvantage but whose cellular telephone received an artificial or prerecorded-voice call from Aidvantage from February 12, 2021 through September 26, 2025.",
        "eligibilityBullets": [
            "You were not an Aidvantage customer when called",
            "Aidvantage placed an artificial or prerecorded-voice call to your cellular telephone",
            "Call occurred from February 12, 2021 through September 26, 2025",
        ],
        "proofRequired": True,
        "proofDetails": "Postcard recipients may file using the personalized claim form sent with their notice. A person who did not receive a postcard must request a claim form in writing and submit proof that an artificial or prerecorded-voice call or message from Aidvantage reached their cellular telephone during the class period.",
        "claimURL": "https://www.aidvantagetcpasettlement.com/",
        "sourceURL": "https://www.aidvantagetcpasettlement.com/",
        "summary": "The settlement resolves claims that Aidvantage placed prerecorded calls to people who were not its customers about another person's student-loan account. Approved claims share the net settlement fund pro rata.",
        "scope": "Nationwide",
        "caseInfo": "Knox v. Maximus Education, LLC, dba Aidvantage, No. 2:25-cv-00121 (M.D. Ala.); administrator Kroll",
        "dateAdded": "2026-08-19",
        "status": "open",
        "claimCount": None,
        "logoURL": favicon("aidvantage.studentaid.gov"),
        "estimatedClaimTime": "~5 min",
        "payoutDisplayType": "details",
    },
    {
        "id": "backchecked-data-breach-2026",
        "title": "BackChecked Data Breach Settlement",
        "company": "BackChecked",
        "imageURL": image("data-breach-generic-2.jpg"),
        "totalAmount": "$535,000",
        "individualPayout": "$50 cash or up to $2,500 plus monitoring",
        "deadline": "2026-08-26",
        "category": "Data Breach",
        "eligibility": "Living individuals residing in the United States whose private information may have been impacted by BackChecked's September 2024 data incident.",
        "eligibilityBullets": [
            "You are a living individual residing in the United States",
            "Your private information was involved in the September 2024 incident",
            "Submit a valid claim by August 26, 2026",
        ],
        "proofRequired": True,
        "proofDetails": "The paper form requests a Class Member ID only if known and requires a signed certification under penalty of perjury; claims are subject to verification. Documented-loss claims require supporting records, while the $50 alternative cash option does not require proof of loss.",
        "claimURL": "https://www.backcheckedsettlement.com/form/claim",
        "sourceURL": "https://www.backcheckedsettlement.com/",
        "summary": "BackChecked agreed to a $535,000 settlement over a September 2024 data incident. Eligible class members may claim a $50 alternative cash payment or documented losses up to $2,500, and may also request one year of three-bureau credit monitoring.",
        "scope": "Nationwide",
        "caseInfo": "Santos, et al. v. Backchecked, LLC, No. CV-24-03690-PHX-JJT (D. Ariz.); administrator Simpluris",
        "dateAdded": "2026-08-19",
        "status": "open",
        "claimCount": None,
        "logoURL": favicon("backchecked.com"),
        "estimatedClaimTime": "~5 min",
        "payoutDisplayType": "upTo",
    },
    {
        "id": "king-county-jail-booking-settlement-2026",
        "title": "King County Jail Booking Settlement",
        "company": "King County",
        "imageURL": image("office-building.jpg"),
        "totalAmount": "$1.6 million",
        "individualPayout": "$150 or at least $1,500, depending on warrants and detention",
        "deadline": "2026-09-01",
        "category": "Consumer",
        "eligibility": "People identified in King County records who were arrested without a warrant and detained in a King County jail for more than 48 hours without a prompt probable-cause determination from January 2, 2021 through April 23, 2025.",
        "eligibilityBullets": [
            "Arrested without a warrant",
            "Detained in a King County jail for more than 48 hours without a prompt probable-cause determination",
            "Detention occurred from January 2, 2021 through April 23, 2025",
        ],
        "proofRequired": True,
        "proofDetails": "Eligibility is limited to people identified in King County records. The online claim verification requires the Notice ID and PIN supplied in the settlement notice.",
        "claimURL": "https://www.kingcountysettlement.com/page/preclaim",
        "sourceURL": "https://www.kingcountysettlement.com/",
        "summary": "King County agreed to settle claims that people arrested without a warrant were held more than 48 hours without a prompt probable-cause determination. Class members without other warrants receive a $1,500 base payment plus $57.81 for each qualifying hour of detention; those with one or more other warrants receive $150.",
        "scope": "King County, Washington",
        "caseInfo": "Tucker et al. v. King County, Washington, No. 2:24-cv-00002-RAJ (W.D. Wash.)",
        "dateAdded": "2026-08-19",
        "status": "open",
        "claimCount": None,
        "logoURL": favicon("kingcounty.gov"),
        "estimatedClaimTime": "~5 min",
        "payoutDisplayType": "details",
    },
    {
        "id": "zoll-heart-device-data-breach-2026",
        "title": "ZOLL Heart-Device Data Breach Settlement",
        "company": "ZOLL Medical",
        "imageURL": image("medical-breach-generic.jpg"),
        "totalAmount": "$3.5 million",
        "individualPayout": "Pro rata cash or up to $5,000",
        "deadline": "2026-09-02",
        "category": "Data Breach",
        "eligibility": "Living United States residents to whom ZOLL Medical issued notice that certain personal information was impacted by its January 2023 data incident.",
        "eligibilityBullets": [
            "You are a living resident of the United States",
            "Your information was potentially affected by the January 2023 incident",
            "ZOLL issued you notice that certain personal information was impacted",
            "Social Security number subclass members receive two shares of the pro rata payment",
        ],
        "proofRequired": True,
        "proofDetails": "The paper form requests a Settlement Claim/Notice ID only if known and requires a signed claim. Out-of-pocket-loss claims up to $5,000 need supporting documentation; pro rata cash eligibility is determined from settlement records.",
        "claimURL": "https://heartdevicedatasettlement.pnclassaction.com/",
        "sourceURL": "https://www.heartdevicedatasettlement.com/",
        "summary": "ZOLL Medical agreed to a $3.5 million settlement over a January 2023 data incident. Class members may seek documented losses up to $5,000 or a pro rata cash payment; members whose Social Security numbers were involved receive two pro rata shares.",
        "scope": "Nationwide",
        "caseInfo": "Smith et al. v. ZOLL Medical Corporation, No. 1:23-cv-10575 (D. Mass.); administrator EisnerAmper",
        "dateAdded": "2026-08-19",
        "status": "open",
        "claimCount": None,
        "logoURL": favicon("zoll.com"),
        "estimatedClaimTime": "~5 min",
        "payoutDisplayType": "upTo",
    },
    {
        "id": "vertical-hold-climbing-gender-settlement-2026",
        "title": "Vertical Hold Climbing Day-Pass Settlement",
        "company": "Vertical Hold Rock Climbing Gym",
        "imageURL": image("gym-fitness.jpg"),
        "totalAmount": "Non-cash settlement",
        "individualPayout": "Four day passes",
        "deadline": "2026-09-03",
        "category": "Consumer",
        "eligibility": "Men and nonbinary people who received direct notice, paid for a Vertical Hold membership or day pass from January 1, 2017 through December 31, 2020, and did not attend Vertical Hold's women's or ladies' clinics, classes, or events.",
        "eligibilityBullets": [
            "Male or nonbinary person who received direct settlement notice",
            "Paid for a Vertical Hold membership or day pass from January 1, 2017 through December 31, 2020",
            "Did not attend Vertical Hold's women's or ladies' clinics, classes, or events",
        ],
        "proofRequired": True,
        "proofDetails": "The claim form requires identifying information and a certification that you satisfy the class definition. Eligibility is limited to people who received direct notice and is checked against Vertical Hold records.",
        "claimURL": "https://verticalholdclassaction.com/form/claim",
        "sourceURL": "https://verticalholdclassaction.com/",
        "summary": "Vertical Hold settled claims concerning women-only or ladies-only climbing events. Eligible men and nonbinary purchasers may submit a claim for four day passes.",
        "scope": "San Diego County, California",
        "caseInfo": "Holsapple, et al. v. Reactor Inc., et al., No. 37-2020-00047212-CU-CR-CTL (San Diego County Superior Court); administrator Simpluris",
        "dateAdded": "2026-08-19",
        "status": "open",
        "claimCount": None,
        "logoURL": favicon("verticalhold.com"),
        "estimatedClaimTime": "~5 min",
        "payoutDisplayType": "details",
    },
    {
        "id": "sportsedtv-video-privacy-settlement-2026",
        "title": "SportsEdTV Video Privacy Settlement",
        "company": "SportsEdTV",
        "imageURL": image("mubi-streaming.jpg"),
        "totalAmount": "$500,000",
        "individualPayout": "Pro rata cash payment; California claims receive two shares",
        "deadline": "2026-09-10",
        "category": "Privacy",
        "eligibility": "The 1,264 United States subscribers identified by SportsEdTV records as having watched videos on the SportsEdTV website from May 9, 2023 through May 16, 2025.",
        "eligibilityBullets": [
            "You are one of the 1,264 identified SportsEdTV subscribers",
            "Watched a video from May 9, 2023 through May 16, 2025",
            "SportsEdTV identified you in its subscriber records",
        ],
        "proofRequired": True,
        "proofDetails": "Use the Login ID and PIN from the notice and certify the claim form. Eligibility is limited to the 1,264 subscribers identified in SportsEdTV's records.",
        "claimURL": "https://sportsedtvsettlement.com/form/claim",
        "sourceURL": "https://sportsedtvsettlement.com/",
        "summary": "SportsEdTV agreed to a $500,000 settlement over alleged disclosure of identified subscribers' video-viewing activity to Meta. Approved California claims receive two pro rata shares and other approved claims receive one share.",
        "scope": "Nationwide",
        "caseInfo": "Balestrieri v. SportsEdTV, Inc., No. 3:25-cv-04046-SK (N.D. Cal.); administrator Simpluris",
        "dateAdded": "2026-08-19",
        "status": "open",
        "claimCount": None,
        "logoURL": favicon("sportsedtv.com"),
        "estimatedClaimTime": "~5 min",
        "payoutDisplayType": "details",
    },
    {
        "id": "acmq-unsolicited-fax-settlement-2026",
        "title": "ACMQ Unsolicited Fax Settlement",
        "company": "American College of Medical Quality",
        "imageURL": image("phone-call-generic.jpg"),
        "totalAmount": "Up to $175,000 for class claims",
        "individualPayout": "Up to $500 per qualifying fax number",
        "deadline": "2026-09-11",
        "category": "Telemarketing",
        "eligibility": "People or entities with fax numbers that were sent one or more faxes in the form of the conference advertisement identified in the lawsuit from August 6 through August 10, 2022.",
        "eligibilityBullets": [
            "Received a fax advertising an ACMQ conference",
            "Fax was received from August 6 through August 10, 2022",
            "Fax matches the advertisement identified as Exhibit A in the case",
        ],
        "proofRequired": True,
        "proofDetails": "Use the Notice ID and PIN if provided, or submit the fax number for verification against the settlement records. Payments are subject to the per-number cap and pro rata adjustment.",
        "claimURL": "https://www.acmqfaxsettlement.com/page/preclaim",
        "sourceURL": "https://www.acmqfaxsettlement.com/",
        "summary": "ACMQ and other defendants settled claims that conference advertisements were sent by fax without permission. Valid claims may receive up to $500 for each verified qualifying fax number, subject to the settlement's $175,000 maximum class recovery and any pro rata adjustment.",
        "scope": "Nationwide",
        "caseInfo": "Loop Spine & Sports Center, Ltd. v. American College of Medical Quality, Inc., et al., No. 22-cv-04198 (N.D. Ill.)",
        "dateAdded": "2026-08-19",
        "status": "open",
        "claimCount": None,
        "logoURL": favicon("acmq.org"),
        "estimatedClaimTime": "~5 min",
        "payoutDisplayType": "upTo",
    },
    {
        "id": "naper-grove-vision-care-data-breach-2026",
        "title": "Naper Grove Vision Care Data Breach Settlement",
        "company": "Naper Grove Vision Care",
        "imageURL": image("medical-breach-generic.jpg"),
        "totalAmount": "$50,000 alternative-cash fund",
        "individualPayout": "Pro rata cash or up to $1,000 plus monitoring",
        "deadline": "2026-09-18",
        "category": "Data Breach",
        "eligibility": "Individuals whose private information may have been impacted by Naper Grove Vision Care's May 2025 data incident.",
        "eligibilityBullets": [
            "Your private information was potentially involved in the incident",
            "The incident occurred in May 2025",
            "Submit a valid claim by September 18, 2026",
        ],
        "proofRequired": True,
        "proofDetails": "The paper form requests a Login ID only if known and requires a signed certification under penalty of perjury; claims are subject to verification. Documented-loss claims up to $1,000 require supporting records, while the alternative cash option requires no proof or explanation.",
        "claimURL": "https://www.napergrovesettlement.com/form/claim",
        "sourceURL": "https://www.napergrovesettlement.com/",
        "summary": "Naper Grove Vision Care agreed to provide benefits over a May 2025 data incident. Eligible class members may choose a pro rata alternative cash payment or seek documented losses up to $1,000 and may request one year of medical-data monitoring.",
        "scope": "Nationwide",
        "caseInfo": "In re Naper Grove Data Breach Litigation, No. 2025-LA-000922 (DuPage County Circuit Court, Illinois); administrator Simpluris",
        "dateAdded": "2026-08-19",
        "status": "open",
        "claimCount": None,
        "logoURL": favicon("napergrove.com"),
        "estimatedClaimTime": "~5 min",
        "payoutDisplayType": "upTo",
    },
    {
        "id": "moodswings-ticket-fee-settlement-2026",
        "title": "Moodswings Ticket-Fee Settlement",
        "company": "Moodswings",
        "imageURL": image("posh-group-tickets.jpg"),
        "totalAmount": "Not publicly stated",
        "individualPayout": "Cash per ticket or a 25% discount code",
        "deadline": "2026-09-18",
        "category": "Consumer",
        "eligibility": "People who bought Moodswings show tickets through tickets.mesmerica.com, tickets.beautifica.show, tickets.changeworlds.org, or ticketshop.mesmerica.com in California, Colorado, Connecticut, Maryland, New York, or Tennessee during the applicable state class period.",
        "eligibilityBullets": [
            "California: July 1, 2024-June 20, 2025; Colorado: August 7, 2024-August 31, 2025",
            "Connecticut: October 1, 2023-August 31, 2025; Maryland: July 1, 2024-June 20, 2025",
            "New York: August 29, 2022-June 20, 2025; Tennessee: July 1, 2023-August 26, 2025",
            "Paid a mandatory fee allegedly not disclosed at the start of the purchase",
        ],
        "proofRequired": True,
        "proofDetails": "Online filing requires the Class Member ID from the settlement notice. Cash is calculated from qualifying ticket purchases in the settlement records and requires a valid claim; doing nothing provides only the 25% discount code.",
        "claimURL": "https://moodswingsticketingsettlement.com/",
        "sourceURL": "https://moodswingsticketingsettlement.com/",
        "summary": "Moodswings settled claims that mandatory electronic-ticket fees were not disclosed at the beginning of the purchase process. Cash amounts are set per ticket by state: $3.37 in California, $2.54 in Colorado, $2.65 in Connecticut, $3.48 in Maryland, $7.12 in New York, and $3.70 in Tennessee. Class members who do not file receive a 25% discount code instead.",
        "scope": "California, Colorado, Connecticut, Maryland, New York, and Tennessee",
        "caseInfo": "Oliva, et al. v. Moodswings, LLC, Index No. 628144/2025 (Nassau County Supreme Court, New York); administrator Kroll",
        "dateAdded": "2026-08-19",
        "status": "open",
        "claimCount": None,
        "logoURL": favicon("moodswingsticketingsettlement.com"),
        "estimatedClaimTime": "~5 min",
        "payoutDisplayType": "details",
    },
    {
        "id": "community-realty-management-data-breach-2026",
        "title": "Community Realty Management Data Breach Settlement",
        "company": "Community Realty Management",
        "imageURL": image("data-breach-generic-3.jpg"),
        "totalAmount": "$200,000 cash-benefit cap",
        "individualPayout": "$20 cash or up to $2,000 plus monitoring",
        "deadline": "2026-09-25",
        "category": "Data Breach",
        "eligibility": "People identified by Community Realty Management as having private information potentially compromised through unauthorized email-account access from September 10 through October 22, 2024, including everyone sent notice of the incident.",
        "eligibilityBullets": [
            "Your private information was potentially involved in accessed email accounts",
            "Unauthorized access occurred from September 10 through October 22, 2024",
            "Community Realty Management identified you as impacted, including by sending an incident notice",
            "Submit a valid claim by September 25, 2026",
        ],
        "proofRequired": True,
        "proofDetails": "The paper form requests a Login ID only if known and requires a signed certification under penalty of perjury; claims are subject to verification. Loss claims up to $2,000 require supporting documentation, while the alternative cash option requires no proof or explanation.",
        "claimURL": "https://crmdatasettlement.com/form/claim/",
        "sourceURL": "https://crmdatasettlement.com/",
        "summary": "Community Realty Management agreed to provide benefits after unauthorized access to email accounts from September through October 2024. Eligible class members may request two years of credit monitoring and choose either an estimated $20 payment or reimbursement for documented losses up to $2,000, subject to the settlement's $200,000 aggregate cash-benefit cap.",
        "scope": "Nationwide",
        "caseInfo": "Barry Alexander v. Community Realty Management, Inc., No. 2026-009398-CA-01 (Miami-Dade County Circuit Court, Florida); administrator Simpluris",
        "dateAdded": "2026-08-19",
        "status": "open",
        "claimCount": None,
        "logoURL": favicon("crmresidential.com"),
        "estimatedClaimTime": "~5 min",
        "payoutDisplayType": "upTo",
    },
    {
        "id": "pierce-county-library-data-breach-2026",
        "title": "Pierce County Library Data Breach Settlement",
        "company": "Pierce County Library System",
        "imageURL": image("data-breach-generic-2.jpg"),
        "totalAmount": "$385,000 cash-benefit cap",
        "individualPayout": "Cash, lost-time payment, or up to $4,000 plus monitoring",
        "deadline": "2026-09-28",
        "category": "Data Breach",
        "eligibility": "Current or former Pierce County Library System employees, their family members, and current or former contractors who were notified that their personal information may have been affected by the cyber incident disclosed in July 2025.",
        "eligibilityBullets": [
            "You are a current or former employee, an employee's family member, or a current or former contractor",
            "Your information was potentially involved in the incident disclosed in July 2025",
            "Pierce County Library System sent you notice",
            "Submit a valid claim by September 28, 2026",
        ],
        "proofRequired": True,
        "proofDetails": "Class membership may be verified with either the unique identifier from the notice or the name and physical address to which the July 2025 notice was sent. Ordinary- and extraordinary-loss claims require third-party documentation, lost time requires an attestation, and alternative cash requires a signed claim.",
        "claimURL": "https://www.piercecountylibrarydatasettlement.com/form/claim",
        "sourceURL": "https://www.piercecountylibrarydatasettlement.com/",
        "summary": "Pierce County Library System agreed to provide benefits over a cyber incident disclosed in July 2025. Eligible class members may request three years of monitoring and claim ordinary losses up to $250, extraordinary losses up to $4,000, lost time at $20 per hour up to $80, or a pro rata alternative cash payment, subject to a $385,000 cash-benefit cap.",
        "scope": "Nationwide",
        "caseInfo": "In re: Pierce County Library System Data Breach Litigation, No. 25-2-11297-2 (Pierce County Superior Court, Washington); administrator Simpluris",
        "dateAdded": "2026-08-19",
        "status": "open",
        "claimCount": None,
        "logoURL": favicon("piercecountylibrary.org"),
        "estimatedClaimTime": "~5 min",
        "payoutDisplayType": "upTo",
    },
    {
        "id": "chemocentryx-securities-settlement-2026",
        "title": "ChemoCentryx Securities Settlement",
        "company": "ChemoCentryx",
        "imageURL": image("office-building.jpg"),
        "totalAmount": "$69 million",
        "individualPayout": "Pro rata securities payment",
        "deadline": "2026-10-01",
        "category": "Financial",
        "eligibility": "People or entities that purchased or otherwise acquired ChemoCentryx common stock from November 26, 2019 through May 6, 2021 and were damaged under the court-approved allocation plan.",
        "eligibilityBullets": [
            "Purchased or acquired ChemoCentryx common stock",
            "Acquisition occurred from November 26, 2019 through May 6, 2021",
            "Suffered a recognized loss under the plan of allocation",
        ],
        "proofRequired": True,
        "proofDetails": "A completed proof-of-claim form and transaction documentation, such as broker confirmations or account statements, are required. Payment depends on the court-approved plan of allocation.",
        "claimURL": "https://chemocentryxsecuritieslitigation.com/",
        "sourceURL": "https://chemocentryxsecuritieslitigation.com/",
        "summary": "A $69 million settlement resolves securities claims concerning ChemoCentryx statements during the class period. Eligible investors must document their transactions and any approved payment will be calculated pro rata under the court-approved plan of allocation.",
        "scope": "Nationwide",
        "caseInfo": "Homyk v. ChemoCentryx, Inc., et al., No. 4:21-cv-03343-JST (N.D. Cal.); administrator Kroll",
        "dateAdded": "2026-08-19",
        "status": "open",
        "claimCount": None,
        "logoURL": favicon("amgen.com"),
        "estimatedClaimTime": "~15 min",
        "payoutDisplayType": "details",
    },
    {
        "id": "credit-suisse-rmbs-restitution-2026",
        "title": "Credit Suisse RMBS Restitution Fund",
        "company": "Credit Suisse",
        "imageURL": image("office-building.jpg"),
        "totalAmount": "$300 million",
        "individualPayout": "Pro rata restitution payment",
        "deadline": "2026-10-06",
        "category": "Financial",
        "eligibility": "Investors that purchased or otherwise acquired certificates in covered Credit Suisse HEMT or HEAT residential mortgage-backed securities trusts before December 18, 2013 and satisfy the distribution plan.",
        "eligibilityBullets": [
            "Purchased or acquired a certificate in a covered HEMT or HEAT trust",
            "Acquisition occurred before December 18, 2013",
            "Meet the requirements of the restitution distribution plan",
        ],
        "proofRequired": True,
        "proofDetails": "A completed claim form and documentation establishing eligible certificate holdings and transactions are required. Awards are calculated under the approved distribution plan.",
        "claimURL": "https://njboscreditsuissesettlement.com/",
        "sourceURL": "https://njboscreditsuissesettlement.com/",
        "summary": "The New Jersey Bureau of Securities established a $300 million restitution fund in its residential mortgage-backed securities matter against Credit Suisse. Investors in covered HEMT and HEAT trust certificates must submit documentation, and approved payments are calculated under the distribution plan.",
        "scope": "Nationwide",
        "caseInfo": "New Jersey Bureau of Securities v. Credit Suisse; consent order and final judgment entered October 24, 2022; administrator A.B. Data",
        "dateAdded": "2026-08-19",
        "status": "open",
        "claimCount": None,
        "logoURL": favicon("credit-suisse.com"),
        "estimatedClaimTime": "~15 min",
        "payoutDisplayType": "details",
    },
    {
        "id": "automotive-information-systems-data-breach-2026",
        "title": "AIS InfoSource Data Breach Settlement",
        "company": "AIS InfoSource",
        "imageURL": image("data-breach-generic-1.jpg"),
        "totalAmount": "Not publicly stated",
        "individualPayout": "Up to $5,000 plus monitoring",
        "deadline": "2026-10-12",
        "category": "Data Breach",
        "eligibility": "People identified in AIS InfoSource records and notified that their private information was potentially involved in its February 2025 data incident.",
        "eligibilityBullets": [
            "Your private information was potentially involved in the February 2025 incident",
            "AIS InfoSource sent you notice",
            "Submit a valid claim by October 12, 2026",
        ],
        "proofRequired": True,
        "proofDetails": "The paper form requests a Login ID only if known and requires a signed certification under penalty of perjury; claims are subject to verification. Documented losses up to $5,000 need supporting records, while lost time requires an attestation and is limited to four hours at $20 per hour.",
        "claimURL": "https://aissettlement.com/form/claim",
        "sourceURL": "https://aissettlement.com/",
        "summary": "AIS InfoSource agreed to provide benefits after a February 2025 data incident. Eligible class members may request two years of credit monitoring, reimbursement for documented losses up to $5,000, and up to $80 for qualifying lost time.",
        "scope": "Nationwide",
        "caseInfo": "Allen, et al. v. AIS InfoSource, L.P., No. 2026-18098 (Harris County District Court, Texas); administrator Simpluris",
        "dateAdded": "2026-08-19",
        "status": "open",
        "claimCount": None,
        "logoURL": favicon("aisinfo.com"),
        "estimatedClaimTime": "~5 min",
        "payoutDisplayType": "upTo",
    },
    {
        "id": "dairy-farmers-america-data-breach-2026",
        "title": "Dairy Farmers of America Data Breach Settlement",
        "company": "Dairy Farmers of America",
        "imageURL": image("data-breach-generic-2.jpg"),
        "totalAmount": "$475,000 cash-payment cap",
        "individualPayout": "Estimated $55 cash or up to $4,500 plus monitoring",
        "deadline": "2026-10-14",
        "category": "Data Breach",
        "eligibility": "United States residents whose private information was compromised in Dairy Farmers of America's June 2025 data incident, including everyone who received notice of the incident.",
        "eligibilityBullets": [
            "Your private information was potentially involved in the June 2025 incident",
            "You reside in the United States",
            "Submit a valid claim by October 14, 2026",
        ],
        "proofRequired": True,
        "proofDetails": "The paper form requests a Login ID only if known and requires a signed certification under penalty of perjury; claims are subject to verification. Documented-loss claims up to $4,500 need supporting records, while the alternative cash option does not require proof of loss.",
        "claimURL": "https://dfadatasettlement.com/form/claim",
        "sourceURL": "https://dfadatasettlement.com/",
        "summary": "Dairy Farmers of America agreed to a $475,000 cash-payment cap and other benefits over a June 2025 data incident. Eligible class members may seek two years of credit monitoring and either an estimated $55 alternative cash payment or documented losses up to $4,500.",
        "scope": "Nationwide",
        "caseInfo": "Jason Buhl v. Dairy Farmers of America, Inc., No. WY-2026-CV-000143 (Wyandotte County District Court, Kansas); administrator Simpluris",
        "dateAdded": "2026-08-19",
        "status": "open",
        "claimCount": None,
        "logoURL": favicon("dfamilk.com"),
        "estimatedClaimTime": "~5 min",
        "payoutDisplayType": "upTo",
    },
    {
        "id": "anixter-center-data-breach-2026",
        "title": "Anixter Center Data Breach Settlement",
        "company": "Lester and Rosalie Anixter Center",
        "imageURL": image("data-breach-generic-3.jpg"),
        "totalAmount": "Not publicly stated",
        "individualPayout": "$50 cash or up to $5,000 plus monitoring",
        "deadline": "2026-10-19",
        "category": "Data Breach",
        "eligibility": "People notified that their private information was compromised in the Anixter Center's July 2023 data incident.",
        "eligibilityBullets": [
            "Your private information was involved in the July 2023 incident",
            "The Anixter Center sent you notice",
            "Submit a valid claim by October 19, 2026",
        ],
        "proofRequired": True,
        "proofDetails": "The paper form requests a Notice ID only if known and requires a signed certification under penalty of perjury; claims are subject to verification. Loss claims up to $5,000 need supporting records, lost time requires an attestation, and the $50 alternative cash option does not require proof of loss.",
        "claimURL": "https://www.anixterdatasettlement.com/form/claim",
        "sourceURL": "https://www.anixterdatasettlement.com/",
        "summary": "The Anixter Center agreed to provide benefits after a July 2023 data incident. Eligible class members may request one year of monitoring and choose a $50 alternative payment or documented losses up to $5,000, including up to $52.50 for qualifying lost time.",
        "scope": "Nationwide",
        "caseInfo": "Cardenas v. Lester and Rosalie Anixter Center, No. 2025LA000252 (Sangamon County Circuit Court, Illinois); administrator Simpluris",
        "dateAdded": "2026-08-19",
        "status": "open",
        "claimCount": None,
        "logoURL": favicon("anixter.org"),
        "estimatedClaimTime": "~5 min",
        "payoutDisplayType": "upTo",
    },
    {
        "id": "washington-county-oregon-tax-foreclosure-2026",
        "title": "Washington County Tax-Foreclosure Settlement",
        "company": "Washington County, Oregon",
        "imageURL": image("lease-document.jpg"),
        "totalAmount": "$1.5 million",
        "individualPayout": "Property-specific surplus payment",
        "deadline": "2026-11-30",
        "category": "Financial",
        "eligibility": "People or entities, and qualifying heirs, successors, assignees, or lienholders, with an ownership interest or valid lien in Washington County, Oregon real property taken through tax foreclosure where the redemption period expired from October 12, 2017 through December 31, 2025 and the County sold the property for surplus proceeds or retained, donated, or transferred property with qualifying surplus equity.",
        "eligibilityBullets": [
            "Held a qualifying ownership interest or valid lien, including through an estate, succession, or assignment",
            "Washington County acquired the property through tax foreclosure and the redemption period expired",
            "The County sold the property for surplus proceeds or retained, donated, or transferred it with qualifying surplus equity",
            "The redemption period expired from October 12, 2017 through December 31, 2025",
        ],
        "proofRequired": True,
        "proofDetails": "Claimants must establish their interest in the property. Heirs, estate representatives, transferees, and other claimants may need probate, title, assignment, or comparable supporting records.",
        "claimURL": "https://washingtonforeclosuresettlement.com/",
        "sourceURL": "https://washingtonforeclosuresettlement.com/",
        "summary": "Washington County agreed to resolve claims over property value retained after tax foreclosures. Under the settlement formula, eligible claims generally receive 100% of surplus proceeds for sold properties or 80% of surplus equity for retained or transferred properties, with applicable interest and permitted deductions determined under the agreement.",
        "scope": "Washington County, Oregon",
        "caseInfo": "Almorn Brackett v. Washington County, No. 3:26-cv-00554-IM (D. Or.); administrator Kroll",
        "dateAdded": "2026-08-19",
        "status": "open",
        "claimCount": None,
        "logoURL": favicon("washingtoncountyor.gov"),
        "estimatedClaimTime": "~10 min",
        "payoutDisplayType": "details",
    },
    {
        "id": "hwwc-medical-data-breach-2026",
        "title": "HWWC Medical Data Breach Settlement",
        "company": "Henderson & Walton Women's Center",
        "imageURL": image("medical-breach-generic.jpg"),
        "totalAmount": "Not publicly stated",
        "individualPayout": "Monitoring and up to $2,500 in documented losses, plus eligible lost time",
        "deadline": "2026-08-27",
        "category": "Data Breach",
        "eligibility": "People whose personal information or protected health information was potentially compromised by unauthorized access to Henderson & Walton Women's Center systems from February 11 through February 14, 2022.",
        "eligibilityBullets": [
            "Personal information or protected health information was potentially compromised",
            "Unauthorized access occurred from February 11 through February 14, 2022",
            "Submit a valid claim by August 27, 2026",
        ],
        "proofRequired": True,
        "proofDetails": "The form asks for the Notice ID and certifies class membership under penalty of perjury. Ordinary and extraordinary loss claims need supporting documentation; up to three hours of lost time at $30 per hour requires the form's attestation.",
        "claimURL": "https://www.hwwcdataincidentsettlement.com/submit-claim",
        "sourceURL": "https://www.hwwcdataincidentsettlement.com/",
        "summary": "Henderson & Walton Women's Center agreed to provide benefits after unauthorized access to its systems in February 2022. Eligible class members may request three years of medical and credit monitoring, reimbursement up to $150 for ordinary losses, up to $2,500 for extraordinary losses, and qualifying lost time up to $90.",
        "scope": "Nationwide",
        "caseInfo": "Townsel v. Henderson & Walton Women's Center, P.C., No. CV-2024-900914.00 (Jefferson County Circuit Court, Alabama); administrator Angeion Group",
        "dateAdded": "2026-08-19",
        "status": "open",
        "claimCount": None,
        "logoURL": favicon("hwwc.com"),
        "estimatedClaimTime": "~5 min",
        "payoutDisplayType": "upTo",
    },
    {
        "id": "mary-black-health-system-settlement-2026",
        "title": "Mary Black Health System Settlement",
        "company": "Mary Black Health System",
        "imageURL": image("lease-document.jpg"),
        "totalAmount": "$2.25 million",
        "individualPayout": "Pro rata share based on approved class-member loss",
        "deadline": "2026-08-31",
        "category": "Healthcare",
        "eligibility": "People who, from January 1, 2014, received healthcare treatment from a defendant-owned or affiliated South Carolina provider while covered by valid health insurance, whose resulting bills were not submitted to that insurer, and who paid the defendants or had a recovery reduced under the challenged policy.",
        "eligibilityBullets": [
            "Received treatment from January 1, 2014 onward at a covered South Carolina provider",
            "Had valid commercial insurance, Medicare, or Medicaid",
            "Bills were not submitted to insurance and you paid or had a recovery reduced",
        ],
        "proofRequired": True,
        "proofDetails": "Use the individualized loss form if one was mailed to you. The public form lists the loss as UNKNOWN and requires claimants to state the claimed loss and attach supporting bills, payment records, or other available documentation; every claim must be signed under penalty of perjury.",
        "claimURL": "https://maryblackclassaction.com/DOCS/MB-Claim-Form.pdf",
        "sourceURL": "https://maryblackclassaction.com/",
        "summary": "A $2.25 million settlement resolves claims concerning amounts paid for certain medical services at Mary Black Health System facilities. Approved claimants share the net settlement fund based on the loss calculation in the settlement documents.",
        "scope": "South Carolina",
        "caseInfo": "Blackwell et al. v. Mary Black Health System, LLC et al., C.A. No. 2017-CP-42-00219 (Spartanburg County Court of Common Pleas, South Carolina); administrator The Notice Company",
        "dateAdded": "2026-08-19",
        "status": "open",
        "claimCount": None,
        "logoURL": favicon("maryblackclassaction.com"),
        "estimatedClaimTime": "~10 min",
        "payoutDisplayType": "details",
    },
    {
        "id": "bestway-above-ground-pool-settlement-2026",
        "title": "Bestway Above-Ground Pool Settlement",
        "company": "Bestway",
        "imageURL": image("bestway-above-ground-pool.png"),
        "totalAmount": "$15 million",
        "individualPayout": "$40 or 10% of qualifying purchase price",
        "deadline": "2026-10-30",
        "category": "Product",
        "eligibility": "People in the United States, its territories, or the District of Columbia who purchased for personal use, and not for resale, a Bestway-branded above-ground pool at least 48 inches tall with compression straps outside the support poles that was sold from 2008 through 2024.",
        "eligibilityBullets": [
            "Bought a qualifying Bestway above-ground pool for personal use",
            "Pool was at least 48 inches tall and had external compression straps",
            "Pool was sold from 2008 through 2024",
            "Secondhand and resale purchases are excluded",
        ],
        "proofRequired": True,
        "proofDetails": "A timely signed claim form certifying the purchase is required. A $40 claim does not require purchase documentation, but a 10% purchase-price claim requires a valid receipt or other proof accepted under the settlement.",
        "claimURL": "https://poolsettlementbw.pnclassaction.com/",
        "sourceURL": "https://www.poolsettlementbw.com/",
        "summary": "Bestway agreed to a $15 million settlement concerning the safety labeling and design of certain above-ground pools with external compression straps. Eligible purchasers may claim $40 without purchase documentation or 10% of the actual or applicable average purchase price with valid proof.",
        "scope": "United States, territories, and District of Columbia",
        "caseInfo": "In re Bestway Above-Ground Pools Litigation, No. 1:25-cv-09570 (N.D. Ill.); administrator EisnerAmper",
        "dateAdded": "2026-08-19",
        "status": "open",
        "claimCount": None,
        "logoURL": favicon("bestwaycorp.com"),
        "estimatedClaimTime": "~5 min",
        "payoutDisplayType": "details",
    },
    {
        "id": "kroger-prescription-savings-club-settlement-2026",
        "title": "Kroger Prescription Savings Club Settlement",
        "company": "Kroger",
        "imageURL": image("metformin-ndma.jpg"),
        "totalAmount": "$17 million",
        "individualPayout": "Pro rata share based on qualifying prescription spending",
        "deadline": "2026-12-21",
        "category": "Healthcare",
        "eligibility": "People who paid all or part of the out-of-pocket cost for a prescription at a Kroger pharmacy using insurance from December 9, 2018 through August 23, 2026 and are included in the settlement class.",
        "eligibilityBullets": [
            "Paid all or part of a prescription's out-of-pocket cost at a Kroger pharmacy",
            "Used insurance for the prescription",
            "Purchase occurred from December 9, 2018 through August 23, 2026",
        ],
        "proofRequired": True,
        "proofDetails": "A notice ID is optional, but the administrator must verify the claim. Claims reporting less than $8,000 in qualifying spending do not require documents up front, although documents may be requested; claims of $8,000 or more require supporting documentation. A claimant without notice credentials who cannot be matched to Kroger's records will be asked for documentation.",
        "claimURL": "https://www.krogersavingsclubsettlement.com/submit-claim",
        "sourceURL": "https://www.krogersavingsclubsettlement.com/",
        "summary": "Kroger agreed to a $17 million settlement over allegations involving insured customers' prescription pricing. Approved payments are calculated pro rata using recognized qualifying out-of-pocket prescription spending under the settlement's allocation rules.",
        "scope": "United States and territories",
        "caseInfo": "Kirkbride et al. v. The Kroger Co., No. 2:21-cv-00022 (S.D. Ohio); administrator Angeion Group",
        "dateAdded": "2026-08-19",
        "status": "open",
        "claimCount": None,
        "logoURL": favicon("kroger.com"),
        "estimatedClaimTime": "~5 min",
        "payoutDisplayType": "details",
    },
]


def main() -> int:
    records = json.loads(FEED.read_text())

    # The official Urban One notice and claim portal give October 12, 2026. The prior
    # August 31 date was from an outdated secondary listing.
    for record in records:
        if record.get("id") == "urban-one-data-breach-2026":
            record["deadline"] = "2026-10-12"
            break
    else:
        raise RuntimeError("urban-one-data-breach-2026 is missing from the source feed")

    new_ids = {record["id"] for record in NEW_RECORDS}
    superseded_ids = {"advanced-recovery-systems-data-breach-2026"}
    records = [
        record for record in records
        if record.get("id") not in new_ids | superseded_ids
    ]
    records.extend(NEW_RECORDS)

    ids = [record["id"] for record in records]
    if len(ids) != len(set(ids)):
        raise RuntimeError("duplicate settlement IDs after update")

    FEED.write_text(json.dumps(records, ensure_ascii=False, indent=2) + "\n")
    print(f"Wrote {len(records)} settlements, including {len(NEW_RECORDS)} reviewed additions")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
